---
# This creates a service so that one can ssh
# into a LB that will connect with the pod.
apiVersion: v1
kind: Service
metadata:
  name: sshd
  namespace: FIXME
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 22
    protocol: TCP
    targetPort: 2222
  selector:
    deploymentconfig: sshd
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0

